server:
  port: xxxx
  mode: debug

datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: canrich
  username: xxx
  password: xxx

redis:
  host: 127.0.0.1
  port: 6379
  password: xxx
  dbName: 0

jwt:
  secretKey: xxx

email:
  username: xxx
  sender: xxx
  password: xxx
  host: xxx
